// flow-typed signature: fed533f730f0f737499b41e64a3f794a
// flow-typed version: <<STUB>>/basic-auth_v2.0.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'basic-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'basic-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'basic-auth/index' {
  declare module.exports: $Exports<'basic-auth'>;
}
declare module 'basic-auth/index.js' {
  declare module.exports: $Exports<'basic-auth'>;
}
