// flow-typed signature: c6539d3a6e5f7be30333c827fe849334
// flow-typed version: <<STUB>>/eslint-plugin-no-only-tests_v^2.0.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-no-only-tests'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-no-only-tests' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-no-only-tests/rules/no-only-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-no-only-tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-no-only-tests/index' {
  declare module.exports: $Exports<'eslint-plugin-no-only-tests'>;
}
declare module 'eslint-plugin-no-only-tests/index.js' {
  declare module.exports: $Exports<'eslint-plugin-no-only-tests'>;
}
declare module 'eslint-plugin-no-only-tests/rules/no-only-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-no-only-tests/rules/no-only-tests'>;
}
declare module 'eslint-plugin-no-only-tests/tests.js' {
  declare module.exports: $Exports<'eslint-plugin-no-only-tests/tests'>;
}
