// flow-typed signature: b03805cc8ec8611795c0e1646ba241a6
// flow-typed version: <<STUB>>/express-useragent_v^1.0.8/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-useragent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-useragent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-useragent/lib/express-useragent' {
  declare module.exports: any;
}

declare module 'express-useragent/lib/express-useragent.min' {
  declare module.exports: any;
}

declare module 'express-useragent/test/android_phone' {
  declare module.exports: any;
}

declare module 'express-useragent/test/android_tablet' {
  declare module.exports: any;
}

declare module 'express-useragent/test/bots_test' {
  declare module.exports: any;
}

declare module 'express-useragent/test/browsers' {
  declare module.exports: any;
}

declare module 'express-useragent/test/express' {
  declare module.exports: any;
}

declare module 'express-useragent/test/http' {
  declare module.exports: any;
}

declare module 'express-useragent/test/silk' {
  declare module.exports: any;
}

declare module 'express-useragent/test/simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-useragent/index' {
  declare module.exports: $Exports<'express-useragent'>;
}
declare module 'express-useragent/index.js' {
  declare module.exports: $Exports<'express-useragent'>;
}
declare module 'express-useragent/lib/express-useragent.js' {
  declare module.exports: $Exports<'express-useragent/lib/express-useragent'>;
}
declare module 'express-useragent/lib/express-useragent.min.js' {
  declare module.exports: $Exports<'express-useragent/lib/express-useragent.min'>;
}
declare module 'express-useragent/test/android_phone.js' {
  declare module.exports: $Exports<'express-useragent/test/android_phone'>;
}
declare module 'express-useragent/test/android_tablet.js' {
  declare module.exports: $Exports<'express-useragent/test/android_tablet'>;
}
declare module 'express-useragent/test/bots_test.js' {
  declare module.exports: $Exports<'express-useragent/test/bots_test'>;
}
declare module 'express-useragent/test/browsers.js' {
  declare module.exports: $Exports<'express-useragent/test/browsers'>;
}
declare module 'express-useragent/test/express.js' {
  declare module.exports: $Exports<'express-useragent/test/express'>;
}
declare module 'express-useragent/test/http.js' {
  declare module.exports: $Exports<'express-useragent/test/http'>;
}
declare module 'express-useragent/test/silk.js' {
  declare module.exports: $Exports<'express-useragent/test/silk'>;
}
declare module 'express-useragent/test/simple.js' {
  declare module.exports: $Exports<'express-useragent/test/simple'>;
}
