// flow-typed signature: 8d305211ac031ebbeb7a3c13de939fc2
// flow-typed version: <<STUB>>/redux-first-router-link_v^1.4.2/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-first-router-link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-first-router-link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-first-router-link/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/dist/handlePress' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/dist/index' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/dist/Link' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/dist/NavLink' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/dist/preventDefault' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/dist/redux-first-router-link' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/dist/redux-first-router-link.min' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/dist/toUrl' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/babel-preset-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/commitizen_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/cz-conventional-changelog_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-flow-vars_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/flow-copy-source_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/history_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/jest_v18.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/jest_v19.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/react-redux_v5.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/react-test-renderer_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/rimraf_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/semantic-release_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/travis-github-status_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-first-router-link/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-first-router-link/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'redux-first-router-link/coverage/lcov-report/prettify'>;
}
declare module 'redux-first-router-link/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'redux-first-router-link/coverage/lcov-report/sorter'>;
}
declare module 'redux-first-router-link/dist/handlePress.js' {
  declare module.exports: $Exports<'redux-first-router-link/dist/handlePress'>;
}
declare module 'redux-first-router-link/dist/index.js' {
  declare module.exports: $Exports<'redux-first-router-link/dist/index'>;
}
declare module 'redux-first-router-link/dist/Link.js' {
  declare module.exports: $Exports<'redux-first-router-link/dist/Link'>;
}
declare module 'redux-first-router-link/dist/NavLink.js' {
  declare module.exports: $Exports<'redux-first-router-link/dist/NavLink'>;
}
declare module 'redux-first-router-link/dist/preventDefault.js' {
  declare module.exports: $Exports<'redux-first-router-link/dist/preventDefault'>;
}
declare module 'redux-first-router-link/dist/redux-first-router-link.js' {
  declare module.exports: $Exports<'redux-first-router-link/dist/redux-first-router-link'>;
}
declare module 'redux-first-router-link/dist/redux-first-router-link.min.js' {
  declare module.exports: $Exports<'redux-first-router-link/dist/redux-first-router-link.min'>;
}
declare module 'redux-first-router-link/dist/toUrl.js' {
  declare module.exports: $Exports<'redux-first-router-link/dist/toUrl'>;
}
declare module 'redux-first-router-link/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/babel-preset-jest_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/babel-preset-jest_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/commitizen_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/commitizen_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/cz-conventional-changelog_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/cz-conventional-changelog_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-flow-vars_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/eslint-plugin-flow-vars_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/flow-copy-source_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/flow-copy-source_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/history_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/history_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/husky_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/jest_v18.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/jest_v18.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/jest_v19.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/jest_v19.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/prettier_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/react-redux_v5.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/react-redux_v5.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/react-test-renderer_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/react-test-renderer_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/redux_v3.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/rimraf_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/rimraf_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/semantic-release_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/semantic-release_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/travis-github-status_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/travis-github-status_vx.x.x'>;
}
declare module 'redux-first-router-link/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'redux-first-router-link/flow-typed/npm/webpack_vx.x.x'>;
}
