// flow-typed signature: 5296d0a11e5da18703d0ac34aad4e0bd
// flow-typed version: <<STUB>>/yaml-frontmatter-loader_v^0.1.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yaml-frontmatter-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yaml-frontmatter-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yaml-frontmatter-loader/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yaml-frontmatter-loader/src/index.js' {
  declare module.exports: $Exports<'yaml-frontmatter-loader/src/index'>;
}
