// flow-typed signature: 7d3ecc4503b7e95368624bc00c838020
// flow-typed version: <<STUB>>/@friends-library/friends_vfriends-library/friends/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@friends-library/friends'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@friends-library/friends' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@friends-library/friends/__tests__/spec.files' {
  declare module.exports: any;
}

// Filename aliases
declare module '@friends-library/friends/__tests__/spec.files.js' {
  declare module.exports: $Exports<'@friends-library/friends/__tests__/spec.files'>;
}
