version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/evans
    steps:
      - checkout
      - restore_cache:
          key: v1-node-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-node-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn test
      - run: node_modules/.bin/webpack --bail --progress --colors --config webpack/client.prod.js
      - run: node_modules/.bin/webpack --bail --progress --colors --config webpack/server.prod.js
